apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: step2-backend-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`shieldx-app.local`)
      kind: Rule
      services:
        - name: step2-backend-service
          port: 80
