apiVersion: v1
kind: Service
metadata:
  name: step2-backend-service
spec:
  type: ClusterIP
  selector:
    app: step2-backend-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
